### ISSUE TITLE
IP Geo Block not providing logs

### ISSUE THREAD

**Issue by wallendorf** [tokkonopapa/WordPress-IP-Geo-Block#1]
I installed the plug-in to my Wordpress site last night.  I love it!  I finally decided that CN and RU were two countries that just were not worth the trouble anymore.  I blacklisted them and a few others and my spam comments went to ZERO overnight.  

My only problem is that I have zero log entries even though I have the setting set to log everything.  What next?

**Comment by tokkonopapa** [comment]
@wallendorf 
Thank you for installing this plugin.
Sorry but UI is little bit ugly. Could you confirm bellow?
`Settings` tab -> `Validation settings` -> `Record validation statistics`: Enable
`Settings` tab -> `Validation settings` -> `Record validation logs`: Only when blocked
Then you can see something on `Statistics` tab and `Logs` tab.

**Comment by wallendorf** [comment]
I confirm those are the settings.  I'm getting statistics, but nothing shows up in the logs.

**Comment by tokkonopapa** [comment]
Hum...
Each of `Statistics` and `Logs` has a different method to save its data into mySQL DB.
So I should write some codes to debug your issue.

Unfortunately, I'll have one week vacation and have a small trip.
I respectfully beg you to giving me some days of grace to do this.

One thing. Could you investigate your wordpress mySQL DB via phpMyAdmin?
If you cound, please find the table __your_prefix__`_ip_geo_block_logs` and see its contents.
If you could not find it, table creation was failed, if you could but its contents are empty, recording was faild.

Thank you.

**Comment by tokkonopapa** [comment]
I updated the version of this plugin to 2.0.7 and added diagnosis of creating a DB table for `Record validation logs`. You'll see the message `Creating a database table for verification log had failed. Once de-activate this plugin, and then activate again` on admin screen if DB creation failed. It means that the timing of DB creation is when this plugin is activated.

So please try a new version and report me about your site's status if you still have any troubles.
Thanks.

**Comment by wallendorf** [comment]
Hey!

 

I updated the plugin, and then deactivated/activated it.  No change.

**Comment by tokkonopapa** [comment]
Ok... then it seems you DB creation had failed.
I need to investigate more about your mysql. Could you tell me the version of your MySQL?

**Comment by wallendorf** [comment]
Version: 5.5.32 | Server Name: angzvacom.fatcowmysql.com 
Databases Available: unlimited | Used: 11

**Comment by tokkonopapa** [comment]
@wallendorf, thank you for your information.
I think your version of mysql is enough to satisfy the requirement (mine is MySQL-5.5.21 :wink:).
I need some time to shoot this issue. Please keep watching this thread!

**Comment by tokkonopapa** [comment]
Hi @wallendorf , I'm sorry to have kept you waiting.
I need your great help to solve this issue. Please follow the step and answer the questions.

### STEP1
#### Please let me know about your site.

Q1.1: Version of PHP.
Q1.2: Version of WordPress.
Q1.3: Are you using multisite feature of WordPress. [Yes/No]
Q1.4: Activated plugins in your site.
      ex: Akismet, Google XML Sitemaps, Meteor Slides, W3 Total Cache, ...

#### Questions about your administrative experiences.

These are very important in order to navigate you to better direction.

Q1.5: You have had some experiences of using phpMyAdmin. [Yes/No]
Q1.6: You can use FTP to upload/download some files to/from your wp-content directory. [Yes/No]

#### Questions about this issue to avoid my misunderstandings.

Q1.7: You can still see the admin notice message `Creating a database table for verification log had failed. Once de-activate this plugin, and then activate again` while activating this plugin. [Yes/No]

### STEP2

I'd like to figure out whether the true cause is inside this plugin or not.

Because there were rare cases which some plugins have blocked the activation process of other plugins.
(I found such issues in the WordPress.org forum. Unfortunately in Japanese.)

If you can de-activate all of plugins you are using, please follow the steps.

S2.1: Make sure you can see the admin notice message (same as Q1.7).
S2.2: De-activate all of your plugins.
S2.3: Activate only this plugin.

Q2: You can still see the admin notice message (same as Q1.7). [Yes/No]

If your answer of Q2 is `No`...
This issue is solved. You can activate all of your plugins again, and done.

If your answer of Q2 is `Yes`...
I'll lead you to **STEP3**.

If you dislike to de-activate all of plugins, I'll also lead you to **STEP3**.

Before we go to **STEP3**, please confirm the above questions.

Again, I'm sorry to bother you so much. I'd like to solve this issue with all my might!
I'll be profoundly grateful your contribution to improve this plugin.
Thanks.

Q1.1: PHP version: 
Q1.2: WordPress version: 
Q1.3: Multisite: [Yes/No]
Q1.4: Your plugins: 
Q1.5: phpMyAdmin: [Yes/No]
Q1.6: FTP: [Yes/No]
Q1.7: admin notice: [Yes/No]
Q2: [Yes/No]

**Comment by wallendorf** [comment]
Sorry I haven’t gotten back to you.  This is kind of my high season if you will.  I’m a turkey hunter, and season starts this weekend.  That’s what the weblog’s all about.  

 

I’ll have to get back to you on this after season ends in about a few weeks.

**Comment by tokkonopapa** [comment]
@wallendorf, I respect your situation. We don't need hurry.
And I truly hope that this season is fruitful for you!

**Comment by tokkonopapa** [comment]
Dear all,
From [release 2.1.2](http://tokkonopapa.github.io/WordPress-IP-Geo-Block/changelog/release-2.1.2.html "2.1.2 Release Note"), debug mode had been implemented to delete or create DB of validation logs.

![Database deletion and creation](http://tokkonopapa.github.io/WordPress-IP-Geo-Block/img/2015-07/plugin-settings.png)

Please embed the following codes in your `functions.php` to use this feature.

```
define( 'IP_GEO_BLOCK_DEBUG', true );
```
