### ISSUE TITLE
Feature: Hide login URL

### ISSUE THREAD

**Issue by ddur** [tokkonopapa/WordPress-IP-Geo-Block#14]
With this (optional) feature
> So many bastard hackers ... 

with automated scripts targeting admin/login would be excluded , like in other security plugins
https://wordpress.org/plugins/search.php?q=hide+login

**Comment by tokkonopapa** [comment]
You can configure to return `404 Not found` status code for each target. Please have a look at http://www.ipgeoblock.com/codex/ip-geo-block-xxxxx-status.html

Isn't it enough for you?

**Comment by ddur** [comment]
No, it is not about me, it is about protection and security.
This is similar to changing standard SSH port from 22 to some not standard port value where it won't be easily found by hackers.

What I mean here is having `/wp-admin` URL renamed.
In combination with IP Geo Block I used another [plugin](https://en-gb.wordpress.org/plugins/wps-hide-login/) that changes 
`http://www.mywordpress.tld/wp-admin`
into 
`http://www.mywordpress.tld/something-else`

So, any automated script that targets `/wp-admin` searching for WordPress sites will find nothing and hopefully give up.

But two plugins have overlapping functionalities (limit number of failed logins) and double impact on performance. I'm not sure if two plugins well cooperate or override each other functionalities.

Sure, I is up to you, will you find this useful feature or not?

**Comment by tokkonopapa** [comment]
Although I can understand your opinion (such as changing default port number), I don't have a plan to implement hiding (or renaming) `/wp-admin` and `wp-login.php`. I know blocking malicious accesses by country code is not enough for protection and security. That's why I combine WP-ZEP for `/wp-admin` and limiting login attempts for `wp-login.php`.

By the way, I read the code of [WPS Hide Login](https://wordpress.org/plugins/wps-hide-login/) and tested it by myself. As the result, here is my opinion:

If someone accesses `/wp-admin` without valid credential, normally WordPress redirect to the login page. And WPS Hide Login is owed to this mechanism and actually doesn't hide `/wp-admin`. It just shows "**This has been disabled**" through `wp_die()`.

Let's assume you have a vulnerable plugin such as [revslider](https://blog.sucuri.net/2014/12/revslider-vulnerability-leads-to-massive-wordpress-soaksoak-compromise.html). Attackers can easily download your `wp-config.php` without knowing user name and password by simple accessing to `/wp-admin/admin-ajax.php?action=revslider_show_image&img=../wp-config.php`. WPS doesn't block this kind of attack.

And WPS doesn't have the functionality of limiting the number of login attempts.

Speaking about hiding login page, basically both IGB and WPS have the same mechanism. They parse requested uri and output a status code (403 or 404) if the condition doesn't match. So I think enabling both plugins is no use but load double impact on performance as you say.

As you know, securing website is not a simple task. And combining multiple security purpose plugins is so hard because [there is no 100% complete solution capable of protecting any environment](https://blog.sucuri.net/2016/10/accounting-for-defense-in-depth-in-website-security.html) :confused:.
