### ISSUE TITLE
Not ISSUES but question :: does this plugin block google index outside my country ip ? 

### ISSUE THREAD

**Issue by navotera** [tokkonopapa/WordPress-IP-Geo-Block#25]
Thanks for your plugin here my question : 
1. Does this plugin blocking google search bot ? Such as google bot that identify outside my country ID (im using whitelist)
2.  Does this plugin blocking request made by authorized wp plugin such as Jetpack or other plugin request ?

**Comment by tokkonopapa** [comment]
Hi @navotera ,

1. No. Please refer to [UA string and Qualification](http://www.ipgeoblock.com/codex/ua-string-and-qualification.html).
2. Yes. Please refer to [Setting for “XML-RPC”](http://www.ipgeoblock.com/codex/the-best-practice-for-target-settings.html "The best practice for target settings") and [How To White List JetPack Servers](https://www.vegard.net/how-to-white-list-jetpack-servers/).

**Comment by navotera** [comment]
Thanks u for your reply sir.. .

Honestly im not sure how this plugin work, i try to access my sites using Proxy in Canada based IP but why it still showing my plugins directory ? 
![image](https://user-images.githubusercontent.com/1424851/35074946-68b29872-fc2b-11e7-96cb-de2f65ca075f.png)



my setting : 
![image](https://user-images.githubusercontent.com/1424851/35075006-b723c38c-fc2b-11e7-803f-2321b06d3ba7.png)

![image](https://user-images.githubusercontent.com/1424851/35074964-7d71e6e6-fc2b-11e7-8d14-a48d72450bcc.png)


let me know im if i miss something

**Comment by tokkonopapa** [comment]
Hi @navotera ,

I think your server software might be nginx, and you have to configure your server not to index the directory at first. This plugin is (of course) a WordPress plugin. So if your server won't start any PHP files (e.g. WordPress), this plugin never works. In your case, your server shows contents of the directory because there's no `index.php` in that directory.

As for the issue of android, 

> why the image operation never success either it view the image or uploading the image...

means:

> why the image operation never success neither viewing the image or uploading the image...

Am I right?

In some cases, mobile browser accesses a page via some kind of proxy server like [Chrome compression server](https://developer.chrome.com/multidevice/data-compression) in order to optimize the speed. So I recommend you to find your blocked access which requested by your android browser in this plugin's "Logs" tab and check the IP address.

Currently, this plugin supports Chrome data saver and [Puffin browser](https://www.puffinbrowser.com/). Please refer to http://www.ipgeoblock.com/changelog/release-3.0.0.html#chrome-compression-proxy and let me know the "**HTTP headers**" of your blocked access in Logs.

**Comment by navotera** [comment]
Im using litespeed server app.  
1. I still dont understand why this plugin still showing my plugin directory event i have blacklisted country ip 
2. I have wp android app ip : here some 
192.0.88.49,192.0.113.210

The problem is i when i type those ip in whitelist ip this plugin still blocked those ip to access some folder as viewed in live update logs

Any config i miss?

**Comment by tokkonopapa** [comment]
> 1. I still dont understand why this plugin still showing my plugin directory event i have blacklisted country ip

Why do you think so? If you have confidence, please let me know. While I know about my plugin very well, I don't have [enough information](https://codex.wordpress.org/Using_the_Support_Forums#Common_Problems_Asking_for_Help " Not Enough Information") about your server. Please let me know [as much information as possible](https://wordpress.org/support/guidelines/#include-as-much-information-as-possible "Forum Guidelines &laquo;  WordPress.org Forums").

> Im using litespeed server app.

OK. Then you can find `/wp-content/plugins/.htaccess` when you enable "**Force to load WP core**" at "**Plugins area**". But in your case, it won't work at all. It means that your server does not allow you to the local `.htaccess`. So please check your server's configuration.

> The problem is i when i type those ip in whitelist ip this plugin still blocked those ip to access some folder as viewed in live update logs

Q1. What kind of message did you see when "you access some folders" ? 
Q2. What did you see at "Result" column in live update logs when your access blocked?
Q3. Where did you access? Please let me know concretely.
Q4. Did you use [mobile app of WordPress for android](https://apps.wordpress.com/mobile/)? The IP addresses `192.0.88.49` and `192.0.113.210` belong to Automattic. So your site is on WordPress.com, right? If so, their server is somewhat special.

The "Result" column is very helpful in order to know [the reason of blocking](http://www.ipgeoblock.com/codex/record-settings-and-logs.html#description-of-result "Record settings and logs | IP Geo Block").

By the way, I'd strongly recommend again to prohibit indexing the folders from the point of view of security.

**Comment by navotera** [comment]
Thanks u for your reply sir... 
Yes i kinda sure this is somehow my mistaken because as i see there was so many people who use this plugin... 
**Q1.** 

im opening this issues because i  dont understand about how this plugin works when i using proxy to simulate that im on US country (blacklisted) but still can show plugin directory. 

Is this normal or this plugin work by disabling direct php execution if it in some plugin directory ? 
Does my server block local .htaccess (i do find .htaccess created by this plugin on my root plugins directory ) ? Does it since .htaccess created by wordpress is working. ?

**for the mobile app** 

Q2. Here my whitelist list config : 
![image](https://user-images.githubusercontent.com/1424851/35175136-33543a06-fd6a-11e7-9eaf-fb35593b1711.png)

and here  result log : 
![image](https://user-images.githubusercontent.com/1424851/35175151-49d8870a-fd6a-11e7-82cf-247aba95311b.png)

Q3. Im accessing in my mobile phone using 4G operator in my country (ID). 

Q4. Yes i am using the official WP android from google play. My site is self hosted wp.

Thanks u sir

**Comment by navotera** [comment]
- Server: LiteSpeed
- PHP: 5.6.33
- PHP SAPI: litespeed
- WordPress: 4.9.2
- Multisite: no
- File system: direct
- Temp folder: /tmp/
- Umask: 755
- Zlib: yes
- ZipArchive: yes
- BC Math: gmp yes
- mb_strcut: yes
- SQLite(PDO): yes
- DNS lookup: available [18.4 msec]
- User agent: Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.89 Safari/537.36
- plugin directory below... (i delete it)

**Comment by tokkonopapa** [comment]
Hi @navotera ,

Thank you for your information. The configuration of your self hosted server seems very strange.

> im opening this issues because i dont understand about how this plugin works when i using proxy to simulate that im on US country (blacklisted)

First of all, I think we have to confirm your server's configuration before thinking about simulating proxy.

> but still can show plugin directory.

This plugin does not have a function to prevent directory listing. That is your server's job which should be configured in your `httpd.conf`.

> Is this normal or this plugin work by disabling direct php execution if it in some plugin directory ?

Yes, if `/wp-content/plugins/.htaccess` works.

> Does my server block local .htaccess (i do find .htaccess created by this plugin on my root plugins directory ) ?

I'm sorry but may be I was wrong. Please put the following code as `index.php` under `/wp-content/plugins/ajax-load-more/`.  You can copy `/wp-content/plugins/index.php`.

```php
<?php
// Silence is golden.
```

And please try to access `/wp-content/plugins/ajax-load-more/` again same as [in this thread](https://github.com/tokkonopapa/WordPress-IP-Geo-Block/issues/25#issuecomment-358499306). Then you might be blocked if you are behind the proxy. It means that if your server parse a PHP file, then "**Force to load WP core**" at "**Plugins area**" and "**Themes area**" works fine. On the other hand, if there's no `index.php` in `/wp-content/plugins/ajax-load-more/`, your server shows the directory listing.

Does it make sense for you?

Regarding to Q2, your image about the result of logs seems very strange because of the following two points.

* This plugin would not handle any files under `/wp-content/upload/`.
* This plugin would not handle any jpg files, but only PHP files.
* The user agent is "Photon/1.0" which is an image acceleration by [Jetpack](https://jetpack.com/support/photon/).

While I have no idea about the cause of the 1st point, the 2nd point would be caused by mismatched content type. I wonder if the content type of jpg is configured as PHP file or something. Please confirm if the content type of jpeg file is `image/jpeg` after disabling this plugin using your browser's developer tool like bellow:

![content-type](https://user-images.githubusercontent.com/828814/35183596-36edd042-fe2c-11e7-8903-51a54fc0a7e4.jpg)
 
And the 3rd point, please try to disable your Jetpack plugin and access it again. I think we have to investigate how Photon works in the site.

**Comment by tokkonopapa** [comment]
Hi,

I tried to replicate your issue under the following conditions, but everything works fine.

- Server: Apache
- PHP: 7.1.8
- PHP SAPI: cgi-fcgi
- WordPress: 4.9.2
- Multisite: no
- File system: direct
- Temp folder: /tmp/
- Umask: 755
- Zlib: yes
- ZipArchive: yes
- BC Math: no
- mb_strcut: yes
- SQLite(PDO): yes
- DNS lookup: available [500.1 msec]
- User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0
- Twenty Twelve Child 1.7
- Twenty Twelve 2.4
- Akismet Anti-Spam 4.0.2
- IP Geo Block 3.0.6.1
- Jetpack by WordPress.com 5.7.1
- Optimize Database after Deleting Revisions 4.5
- WP Multibyte Patch 2.8.1

### Android ###

- Version: 4.1.2
- Browser: Default browser

### Mobile App for WordPress ###

- iOS 11.2.2
- [WordPress.com App](https://apps.wordpress.com/mobile/)

### Validation rule settings ###
![jetpack-rule](https://user-images.githubusercontent.com/828814/35193584-13031bbc-fee8-11e7-92b9-1dd4dd9d23b6.png)

### Back-end target settings ###
![jetpack-backend](https://user-images.githubusercontent.com/828814/35193589-26229dbc-fee8-11e7-9f38-93631ef03627.png)

### Front-end target settings ###
![jetpack-frontend](https://user-images.githubusercontent.com/828814/35193594-3229be42-fee8-11e7-989e-3ea619e20c03.png)

### Logs (accessed by WordPress.com App) ###
![jetpack-logs](https://user-images.githubusercontent.com/828814/35193597-41e21d98-fee8-11e7-9338-70adceae6544.png)

### Side Note ###
You can use the CIDR notation `192.0.64.0/18` to specify the Automattic server.

![jetpack-automattic](https://user-images.githubusercontent.com/828814/35193612-751896ba-fee8-11e7-8f6f-696672db1abe.png)

And here is the related documents:

* [Photon](https://developer.wordpress.com/docs/photon/ "Photon | Developer Resources")
* [Photon API](https://developer.wordpress.com/docs/photon/api/ "Photon API | Developer Resources")

**Comment by navotera** [comment]
Thanks u sir... i will test this, if not work i guess it somehow related to my server configuration 

thanks u again

**Comment by navotera** [comment]
sorry i dont have time for a while to test this so i close this

by the way thanks for your cooperation.. 
have a nice days !
